"$schema" = "node_modules/wrangler/config-schema.json"
name = "chktime"
main = "src/index.js"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./public"

[[routes]]
pattern = "chktime.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "mindb"
database_id = "64a01a5b-bab5-4f70-a226-2b6d5e919721"

[[hyperdrive]]
binding = "HH_DB"
id = "e59a2e35c40147149fa08190a6a5de40"
localConnectionString = "mysql://bb:bb!!21!!22@61.253.226.125:3306/bb"