"$schema" = "node_modules/wrangler/config-schema.json"
name = "chktime"
main = "src/index.ts"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./public"

[[routes]]
pattern = "chktime.com"
custom_domain = true